#!/usr/bin/env bash
# Shared defaults for every non-GPT Sculptor model-family simulation.
# Export any variable before run-test.sh or run-all.sh to override it.

: "${GOLEM_MODEL_MEMORY_BACKEND:=native}"
: "${GOLEM_MODEL_TILE_MEMORY:=64M}"
: "${GOLEM_MODEL_CPU_CLOCK:=1GHz}"
: "${GOLEM_MODEL_CPU_ISSUE_WIDTH:=1}"
: "${GOLEM_MODEL_SYNC_INSTRUCTION_QUANTUM:=1000}"
: "${GOLEM_MODEL_MESH_ROWS:=1}"
: "${GOLEM_MODEL_MESH_COLS:=1}"
: "${GOLEM_MODEL_DIGITAL_WORKERS:=1}"
: "${GOLEM_MODEL_BALANCE_DIGITAL_WORK:=0}"
: "${GOLEM_MODEL_PLANNER_STRATEGIES:=setup-first,mvm-wave,fan-out-cut,consumer-bound-fill}"
: "${GOLEM_MODEL_SST_THREADS:=1}"
: "${GOLEM_MODEL_SST_PARTITIONER:=sst.simple}"

# Empty dimensions select the shared 1024x512 default for every fixture.
: "${GOLEM_MODEL_ARRAY_ROWS:=}"
: "${GOLEM_MODEL_ARRAY_COLS:=}"
: "${GOLEM_MODEL_ARRAYS_PER_CORE:=4}"
: "${GOLEM_MODEL_ANALOG_BACKEND:=native}"
: "${GOLEM_MODEL_ANALOG_LINK_CLOCK:=1GHz}"
: "${GOLEM_MODEL_ANALOG_COMPUTE_LATENCY_CYCLES:=100}"
: "${GOLEM_MODEL_DUPLICATE_MATRICES:=0}"

: "${GOLEM_MODEL_MESH_LINK_WIDTH_BITS:=32}"
: "${GOLEM_MODEL_MESH_LINK_CLOCK:=1GHz}"
: "${GOLEM_MODEL_NETWORK_CELL_WORDS:=1}"
: "${GOLEM_MODEL_NETWORK_BUFFER_CELLS:=16}"
# Empty value uses the network buffer capacity.
: "${GOLEM_MODEL_NETWORK_PACKET_WORDS:=}"
: "${GOLEM_MODEL_MESH_ROUTER_BACKEND:=mittens}"
: "${GOLEM_MODEL_MESH_LINK_LATENCY:=1ns}"
: "${GOLEM_MODEL_WORMHOLE_INPUT_BUFFER_FLITS:=32}"
: "${GOLEM_MODEL_WORMHOLE_INJECTION_BUFFER_FLITS:=64}"
: "${GOLEM_MODEL_WORMHOLE_PIPELINE_CYCLES:=3}"
: "${GOLEM_MODEL_RX_DMA_WIDTH_BITS:=256}"
: "${GOLEM_MODEL_RX_DMA_SETUP_CYCLES:=8}"
: "${GOLEM_MODEL_RX_DMA_QUEUE_DEPTH:=4}"

: "${GOLEM_MODEL_RVV_ENABLED:=true}"
: "${GOLEM_MODEL_RVV_LENGTH_BITS:=256}"
: "${GOLEM_MODEL_RVV_ELEMENT_BITS:=64}"
: "${GOLEM_MODEL_SCRATCHPAD_ENABLED:=false}"

# off, summary, or trace. Trace emits per-tile task and performance CSV files.
: "${GOLEM_MODEL_PROFILE_MODE:=off}"

# Used only with GOLEM_MODEL_MEMORY_BACKEND=memhierarchy.
: "${GOLEM_MODEL_MEMORY_INIT_BATCHING:=true}"
: "${GOLEM_MODEL_MEMORY_ACCESS_BATCHING:=false}"
: "${GOLEM_MODEL_MEMORY_ACCESS_BATCH_RECORDS:=16}"
: "${GOLEM_MODEL_MEMORY_INIT_BYTES_PER_CYCLE:=32}"
: "${GOLEM_MODEL_MEMORY_INIT_LATENCY_CYCLES:=2}"
: "${GOLEM_MODEL_L1_SIZE:=32KiB}"
: "${GOLEM_MODEL_L1_ASSOCIATIVITY:=4}"
: "${GOLEM_MODEL_CACHE_LINE_SIZE:=64}"
: "${GOLEM_MODEL_L1_ACCESS_LATENCY_CYCLES:=2}"
: "${GOLEM_MODEL_L1_CLOCK:=1GHz}"
: "${GOLEM_MODEL_LOWER_MEMORY_CLOCK:=1GHz}"
: "${GOLEM_MODEL_LOWER_MEMORY_ACCESS_TIME:=50ns}"
