#!/usr/bin/env python3
"""Run the real Phase-5 scalar classifier before tile/ELF code generation.

The input boundary is the canonical ``deployment/08-placed.mlir`` artifact.
Each artifact is outlined in memory with the production Phase-5 policy, then
the split driver emits only its compact scalar eligibility audit.  No per-tile
IR, LLVM IR, object, ELF, QEMU, or SST artifact is generated by this preflight.

This is an early failure detector, not a replacement for the full compile,
ABI, memory, accounting, or SST qualification gates.
"""

from __future__ import annotations

import argparse
import json
import os
from pathlib import Path
import subprocess
import sys
import tempfile
import time
from typing import Any


CANONICAL_MODELS = (
    "resnet32",
    "wide-resnet-16-8",
    "resnet50",
    "yolov9-c",
    "retinanet",
    "rnnt",
    "mobilebert",
    "bert-large",
)
EXPECTED_SCALAR_PLAN_VERSION = 3
SUMMARY_KEYS = {
    "scalar_plan_version",
    "scalar_eligible_region_count",
    "scalar_fallback_region_count",
    "scalar_selected_region_count",
    "scalar_removed_kernel_count",
}


class PreflightError(RuntimeError):
    """A fail-closed artifact or summary error."""


def positive_integer(value: str) -> int:
    parsed = int(value)
    if parsed <= 0:
        raise argparse.ArgumentTypeError("must be a positive integer")
    return parsed


def parse_artifact(value: str) -> tuple[str, Path]:
    model, separator, filename = value.partition("=")
    if not separator or not model or not filename:
        raise argparse.ArgumentTypeError("expected MODEL=deployment/08-placed.mlir")
    if model not in CANONICAL_MODELS:
        raise argparse.ArgumentTypeError(f"unknown canonical model: {model}")
    return model, Path(filename)


def load_campaign_artifacts(path: Path) -> dict[str, Path | None]:
    try:
        payload = json.loads(path.read_text(encoding="utf-8"))
    except (OSError, json.JSONDecodeError) as error:
        raise PreflightError(f"cannot read campaign summary {path}: {error}") from error
    if not isinstance(payload, dict) or not isinstance(payload.get("models"), list):
        raise PreflightError("campaign summary must contain a models array")

    artifacts: dict[str, Path | None] = {model: None for model in CANONICAL_MODELS}
    seen: set[str] = set()
    for record in payload["models"]:
        if not isinstance(record, dict):
            raise PreflightError("campaign summary contains a malformed model row")
        model = record.get("model")
        if model not in CANONICAL_MODELS:
            raise PreflightError(f"campaign summary contains unknown model: {model!r}")
        if model in seen:
            raise PreflightError(f"campaign summary repeats model: {model}")
        seen.add(model)
        run_directory = record.get("run_directory")
        if isinstance(run_directory, str) and run_directory:
            artifacts[model] = Path(run_directory) / "deployment" / "08-placed.mlir"
    return artifacts


def explicit_artifacts(values: list[tuple[str, Path]]) -> dict[str, Path | None]:
    artifacts: dict[str, Path | None] = {model: None for model in CANONICAL_MODELS}
    for model, path in values:
        if artifacts[model] is not None:
            raise PreflightError(f"duplicate artifact for model: {model}")
        artifacts[model] = path
    missing = [model for model, path in artifacts.items() if path is None]
    if missing:
        raise PreflightError(
            "explicit artifact set must cover all eight canonical models; missing: "
            + ", ".join(missing)
        )
    return artifacts


def command_for(tool: Path, artifact: Path, debug_timing: bool) -> list[str]:
    command = [
        str(tool),
        str(artifact),
        "--outline-placed-deployment",
        "--outline-sequence-waves-in-flight=1",
        "--outline-specialize-conv-patch-generation",
        "--outline-contract-scalar-execution-regions",
        "--outline-consolidate-layer-regions",
        "--outline-retain-proved-local-owners",
        "--outline-exact-ram-readiness",
        "--outline-scalar-summary-only",
    ]
    if debug_timing:
        command.append("--outline-debug-phase-timing")
    return command


def parse_summary(stdout: str) -> dict[str, int]:
    parsed: dict[str, int] = {}
    for line in stdout.splitlines():
        key, separator, raw_value = line.partition("=")
        if not separator or key not in SUMMARY_KEYS or key in parsed:
            raise PreflightError(f"malformed scalar summary line: {line!r}")
        try:
            value = int(raw_value)
        except ValueError as error:
            raise PreflightError(f"non-integer scalar summary value: {line!r}") from error
        if value < 0:
            raise PreflightError(f"negative scalar summary value: {line!r}")
        parsed[key] = value
    if set(parsed) != SUMMARY_KEYS:
        missing = sorted(SUMMARY_KEYS - set(parsed))
        extra = sorted(set(parsed) - SUMMARY_KEYS)
        raise PreflightError(
            f"scalar summary fields disagree: missing={missing} extra={extra}"
        )
    if parsed["scalar_plan_version"] != EXPECTED_SCALAR_PLAN_VERSION:
        raise PreflightError(
            "scalar summary schema is stale: "
            f"expected={EXPECTED_SCALAR_PLAN_VERSION} "
            f"actual={parsed['scalar_plan_version']}"
        )
    eligible = parsed["scalar_eligible_region_count"]
    fallback = parsed["scalar_fallback_region_count"]
    selected = parsed["scalar_selected_region_count"]
    if eligible + fallback != selected:
        raise PreflightError(
            "scalar summary does not partition selected regions: "
            f"eligible={eligible} fallback={fallback} selected={selected}"
        )
    if eligible == 0 and parsed["scalar_removed_kernel_count"] != 0:
        raise PreflightError(
            "scalar summary removes kernels without an eligible region"
        )
    return parsed


def diagnostic_tail(value: str, limit: int = 8192) -> str:
    return value[-limit:]


def malformed_result(
    model: str,
    artifact: Path | None,
    reason: str,
    *,
    elapsed_seconds: float = 0.0,
    command: list[str] | None = None,
    exit_code: int | None = None,
    stderr: str = "",
) -> dict[str, Any]:
    return {
        "model": model,
        "status": "MALFORMED",
        "artifact": str(artifact) if artifact is not None else None,
        "artifact_size_bytes": None,
        "elapsed_seconds": round(elapsed_seconds, 6),
        "exit_code": exit_code,
        "command": command,
        "eligible_region_count": None,
        "fallback_region_count": None,
        "selected_region_count": None,
        "removed_kernel_count": None,
        "malformed_artifact_count": 1,
        "reason": reason,
        "diagnostic_tail": diagnostic_tail(stderr),
    }


def run_preflight(
    model: str,
    artifact: Path | None,
    tool: Path,
    timeout_seconds: int,
    debug_timing: bool,
) -> dict[str, Any]:
    if artifact is None:
        return malformed_result(model, artifact, "campaign has no run directory")
    try:
        artifact_size = artifact.stat().st_size
    except OSError as error:
        return malformed_result(model, artifact, f"cannot stat artifact: {error}")
    if not artifact.is_file() or artifact_size == 0:
        return malformed_result(model, artifact, "artifact is not a nonempty regular file")

    command = command_for(tool, artifact, debug_timing)
    started = time.monotonic()
    try:
        completed = subprocess.run(
            command,
            check=False,
            capture_output=True,
            text=True,
            timeout=timeout_seconds,
        )
    except subprocess.TimeoutExpired as error:
        elapsed = time.monotonic() - started
        stderr = error.stderr or ""
        if isinstance(stderr, bytes):
            stderr = stderr.decode("utf-8", errors="replace")
        return malformed_result(
            model,
            artifact,
            f"scalar preflight exceeded {timeout_seconds} seconds",
            elapsed_seconds=elapsed,
            command=command,
            stderr=stderr,
        )
    except OSError as error:
        return malformed_result(
            model,
            artifact,
            f"cannot execute scalar preflight: {error}",
            command=command,
        )
    elapsed = time.monotonic() - started
    if completed.returncode != 0:
        return malformed_result(
            model,
            artifact,
            "compiler rejected the artifact before producing a complete scalar audit",
            elapsed_seconds=elapsed,
            command=command,
            exit_code=completed.returncode,
            stderr=completed.stderr,
        )
    try:
        summary = parse_summary(completed.stdout)
    except PreflightError as error:
        return malformed_result(
            model,
            artifact,
            str(error),
            elapsed_seconds=elapsed,
            command=command,
            exit_code=completed.returncode,
            stderr=completed.stderr,
        )
    return {
        "model": model,
        "status": "PASS",
        "artifact": str(artifact.resolve()),
        "artifact_size_bytes": artifact_size,
        "elapsed_seconds": round(elapsed, 6),
        "exit_code": completed.returncode,
        "command": command,
        "scalar_plan_version": summary["scalar_plan_version"],
        "eligible_region_count": summary["scalar_eligible_region_count"],
        "fallback_region_count": summary["scalar_fallback_region_count"],
        "selected_region_count": summary["scalar_selected_region_count"],
        "removed_kernel_count": summary["scalar_removed_kernel_count"],
        "malformed_artifact_count": 0,
        "reason": None,
        "diagnostic_tail": diagnostic_tail(completed.stderr),
    }


def write_json_atomic(path: Path, payload: dict[str, Any]) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    descriptor, temporary_name = tempfile.mkstemp(
        prefix=f".{path.name}.", suffix=".tmp", dir=path.parent
    )
    try:
        with os.fdopen(descriptor, "w", encoding="utf-8") as stream:
            json.dump(payload, stream, indent=2, sort_keys=True)
            stream.write("\n")
        os.replace(temporary_name, path)
    except BaseException:
        try:
            os.unlink(temporary_name)
        except FileNotFoundError:
            pass
        raise


def build_parser() -> argparse.ArgumentParser:
    project_root = Path(__file__).resolve().parents[2]
    parser = argparse.ArgumentParser(description=__doc__)
    source = parser.add_mutually_exclusive_group(required=True)
    source.add_argument(
        "--campaign-summary",
        type=Path,
        help="canonical compiler/full-model summary JSON used to locate run artifacts",
    )
    source.add_argument(
        "--artifact",
        action="append",
        default=[],
        type=parse_artifact,
        metavar="MODEL=PATH",
        help="explicit canonical placed artifact; repeat exactly eight times",
    )
    parser.add_argument(
        "--split-tool",
        type=Path,
        default=project_root / "install" / "sculptor-mlir" / "bin"
        / "sculptor-split-tile-deployment",
    )
    parser.add_argument("--timeout-seconds", type=positive_integer, default=300)
    parser.add_argument("--output-json", type=Path)
    parser.add_argument("--debug-phase-timing", action="store_true")
    return parser


def main(argv: list[str] | None = None) -> int:
    parser = build_parser()
    args = parser.parse_args(argv)
    try:
        artifacts = (
            load_campaign_artifacts(args.campaign_summary)
            if args.campaign_summary is not None
            else explicit_artifacts(args.artifact)
        )
    except PreflightError as error:
        parser.error(str(error))

    tool = args.split_tool
    if not tool.is_file() or not os.access(tool, os.X_OK):
        parser.error(f"split tool is not executable: {tool}")

    results = [
        run_preflight(
            model,
            artifacts[model],
            tool,
            args.timeout_seconds,
            args.debug_phase_timing,
        )
        for model in CANONICAL_MODELS
    ]
    malformed = sum(result["malformed_artifact_count"] for result in results)
    eligible = sum(result["eligible_region_count"] or 0 for result in results)
    fallback = sum(result["fallback_region_count"] or 0 for result in results)
    selected = sum(result["selected_region_count"] or 0 for result in results)
    status = "PASS" if malformed == 0 else "FAIL"
    report = {
        "schema": "sculptor.phase5-suite-preflight",
        "schema_version": 1,
        "status": status,
        "checkpoint": "deployment/08-placed.mlir -> scalar-region-contraction",
        "canonical_models": list(CANONICAL_MODELS),
        "split_tool": str(tool.resolve()),
        "timeout_seconds_per_model": args.timeout_seconds,
        "qualification_scope": {
            "exercises_real_physical_family_classifier": True,
            "skips_per_tile_serialization": True,
            "skips_llvm_object_elf_codegen": True,
            "replaces_full_compile_abi_memory_sst_gates": False,
        },
        "totals": {
            "eligible_region_count": eligible,
            "fallback_region_count": fallback,
            "selected_region_count": selected,
            "malformed_artifact_count": malformed,
        },
        "results": results,
    }
    if eligible + fallback != selected:
        raise AssertionError("coherent model summaries produced incoherent totals")
    if args.output_json is not None:
        write_json_atomic(args.output_json, report)

    for result in results:
        print(
            f"{result['model']},{result['status']},"
            f"eligible={result['eligible_region_count']},"
            f"fallback={result['fallback_region_count']},"
            f"malformed={result['malformed_artifact_count']},"
            f"selected={result['selected_region_count']},"
            f"wall_seconds={result['elapsed_seconds']:.6f}"
        )
    print(
        f"phase5-suite-preflight,{status},eligible={eligible},"
        f"fallback={fallback},malformed={malformed},selected={selected}"
    )
    return 0 if status == "PASS" else 1


if __name__ == "__main__":
    sys.exit(main())
